[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://webirent.netlify.app"
  NODE_VERSION = "18"
  NEXTAUTH_URL = "https://croo-rent.netlify.app/"
  NEXTAUTH_SECRET = "3+IY2CIIux+aXQtLSrXf3Fux9b/ivHOMsDn1Z+xLqos="

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 